repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']

  - repo: https://github.com/omnilib/ufmt
    rev: v2.6.0
    hooks:
    -   id: ufmt
        additional_dependencies:
          - black == 24.4.2
          - usort == 1.0.5

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--config=.flake8]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.3
    hooks:
      - id: clang-format
        name: clang-format
        files: \.(cpp|hpp|c|h)$
        types: [file]
