[mypy]

files = src/torchcodec
show_error_codes = True
pretty = True
allow_redefinition = True
follow_untyped_imports = True
strict = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-torchvision.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-torchcodec._core.ops]
disable_error_code = untyped-decorator, no-any-return, no-untyped-def
