name: Unit-tests on Linux GPU
on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:
jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.9"]
        # TODO: Add more CUDA versions.
        cuda_arch_version: ["12.4"]
        ffmpeg_version: ["origin/release/6.1"]
      fail-fast: false
    runs-on: [ self-hosted, linux, gpu ]
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          conda install --quiet --yes pip cmake pkg-config nasm
          pip install --quiet --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu124
          conda install --quiet --yes nvidia::libnpp

      - name: Check NVIDIA driver presence
        run: nvidia-smi

      - name: Build and install FFMPEG from source
        run: |
          git clone --quiet https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
          pushd nv-codec-headers
          make --silent PREFIX=$CONDA_PREFIX -j install
          popd
          git clone --quiet https://git.ffmpeg.org/ffmpeg.git ffmpeg/
          pushd ffmpeg
          git checkout ${{ matrix.ffmpeg_version }}
          ./configure --prefix=$CONDA_PREFIX --enable-nonfree --enable-cuda-nvcc --disable-static --enable-shared --optflags=-fno-omit-frame-pointer --disable-stripping --enable-cuvid --enable-rpath
          make --silent -j install
          popd

      - name: Run tests
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=8
          export CXXFLAGS=""
          export LDFLAGS="-Wl,--allow-shlib-undefined -Wl,-rpath,$CONDA_PREFIX/lib -Wl,-rpath-link,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib"
          export CMAKE_BUILD_TYPE=Release
          export ENABLE_CUDA=1
          pip install -e ".[dev]" --no-build-isolation -vv --debug
          pytest -k "not (test_get_metadata or get_ffmpeg_version)" -vvv

      - name: Clean up
        run: conda deactivate
