name: Docs

on:
  push:
    branches: [ main ]
  pull_request:

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  build:
    runs-on: linux.g5.4xlarge.nvidia.gpu
    strategy:
      fail-fast: false
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: '3.12'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install torchcodec from nightly
        run: |
          pip3 install --pre torch torchvision torchaudio torchcodec --index-url https://download.pytorch.org/whl/nightly/cu124
      - name: Install FFMPEG
        run: |
          conda install ffmpeg=7 -c conda-forge
          ffmpeg -version
      - name: Install doc dependencies
        run: |
          cd docs
          python -m pip install -r requirements.txt
      - name: Build docs
        run: |
          cd docs
          make html
      - uses: actions/upload-artifact@v3
        with:
          name: Built-Docs
          path: docs/build/html/
